#!/usr/bin/env ruby
# coding: utf-8
require 'yaml'
require 'tempfile'
require 'fileutils'
require 'socket'
require 'optparse'

opt = OptionParser.new()
options = {}
opt.on('-c config', '(必須)設定ファイルのパス') {|v| options[:config] = v}
opt.on('-s script', '(必須)実行するスクリプトのパス') {|v| options[:script] = v}
opt.on('-n name', '(必須)実行する処理の識別子、出力先やテンポラリディレクトリの名前を識別するのに使う') {|v| options[:name] = v}
opt.on('-o [output]', '結果の出力先、デフォルトではカレントディレクトリの dench.name に出力') {|v| options[:output] = v}
opt.on('-p [params]', 'パラメータファイルのパス') {|v| options[:params] = v}
opt.parse!(ARGV)

name = options[:name]
config_path = options[:config]
script_path = options[:script]
parameter_path = options[:params]
output = options[:output] || "dench.output.#{name}"
parameters = []
unless File.exist?(config_path)
  STDERR.puts("#{config_path} does not exist.")
  exit(1)
end
unless File.exist?(script_path)
  STDERR.puts("#{script_path} does not exist.")
  exit(1)
end
if parameter_path.instance_of?(String)
  unless File.exist?(parameter_path)
    STDERR.puts("#{parameter_path} does not exist.")
    exit(1)
  end
  parameters = File.read(parameter_path).split("\n")
end
if (File.exist?(output))
  STDERR.puts("output directory #{output} already exist.")
  exit(1)
end

class DenchNode
  attr_reader :id, :host, :process, :wd

  def initialize(id, host, process)
    @id = id
    @host = host
    @process = process
    @wd = "/tmp/dench.#{@host}.#{@id}" # FIXME
  end

  public
  def prepare()
    mkdir = "ssh #{@host} 'mkdir -p #{@wd}'"
    puts(mkdir)
    system(mkdir)
  end

  def finalize()
    rm = "ssh #{@host} rm -rf #{@wd}"
    puts(rm)
    system(rm)
  end

  def push(src, dst)
    scp = "scp -r #{src} #{@host}:#{@wd}/#{dst}"
    puts(scp)
    system(scp)
  end

  def pullall(dst)
    scp = "scp -r #{@host}:#{@wd} #{dst}"
    puts(scp)
    system(scp)
  end

  def exec(cmd)
    ssh = "ssh #{@host} 'cd #{@wd}; #{cmd}'"
    puts(ssh)
    system(ssh)
  end

  def to_s()
    "-#{@host}: process = #{@process}"
  end
end

# FIXME
class DenchPreprocess
  attr_accessor :dench, :node

  def initialize()
    @dench = nil
    @node = nil
  end

  public
  def to_s()
    [
      "-dench: #{@dench}",
      "-node: #{@node}",
    ].join("\n")
  end
end

# FIXME
class DenchPostprocess
  attr_accessor :dench, :node

  def initialize()
    @dench = nil
    @node = nil
  end

  public
  def to_s()
    [
      "-dench: #{@dench}",
      "-node: #{@node}",
    ].join("\n")
  end
end

class DenchConfig
  attr_reader :nodes, :preprocess, :postprocess, :name

  def initialize(name, config_hash)
    @name = name
    @nodes = parse_node_config(config_hash)
    @preprocess = parse_preprocess_config(config_hash)
    @postprocess = parse_postprocess_config(config_hash)
  end

  public
  def self.parse(name, config_hash)
    self.new(name, config_hash)
  end

  private
  def parse_node_config(config_hash)
    unless config_hash['nodes']
      raise("invalid config: nodes are not specified")
    end
    id = 0
    config_hash['nodes'].map{|s|
      host = s['host']
      unless host 
        raise("invalid config: host is not specified")
      end
      process = s['process']
      unless process
        raise("invalid config: process is not specified")
      end
      DenchNode.new("#{@name}_#{id += 1}", host, process)
    }
  end

  # FIXME
  def parse_preprocess_config(config_hash)
    preprocess = DenchPreprocess.new()
    preprocess_config = config_hash['preprocess']
    return preprocess unless preprocess_config
    if preprocess_config['dench']
      preprocess.dench = preprocess_config['dench']
    end
    if preprocess_config['node']
      preprocess.node = preprocess_config['node']
    end
    preprocess
  end

  # FIXME
  def parse_postprocess_config(config_hash)
    postprocess = DenchPostprocess.new()
    postprocess_config = config_hash['postprocess']
    return postprocess unless postprocess_config
    if postprocess_config['dench']
      postprocess.dench = postprocess_config['dench']
    end
    if postprocess_config['node']
      postprocess.node = postprocess_config['node']
    end
    postprocess
  end

  def to_s()
    [
      "---------- nodes ----------",
      @nodes,
      "---------- preprocess ----------",
      @preprocess,
    ].flatten.join("\n")
  end
end

class DenchPackage
  attr_reader :script

  def initialize(script, tmpdir)
    @script = script
    @tmpdir = tmpdir
  end

  public
  def self.create(script_path, runner)
    tmpdir = Dir.mktmpdir(nil, Dir.getwd())
    script = File.basename(script_path)
    package = DenchPackage.new(script, tmpdir)
    FileUtils.copy(script_path, File.join(tmpdir, 'command.sh'))
    File.write(File.join(tmpdir, 'runner.sh'), runner)
    package
  end

  def destroy()
    FileUtils.remove_entry_secure(@tmpdir)
  end

  def to_s()
    @tmpdir.to_s()
  end
end

class DenchProcess
  attr_reader :id, :node, :params

  def initialize(id, node, script_path, params)
    @id = id
    @node = node
    @script_path = script_path
    @params = params
    @remote_tmpdir = File.join(@node.wd, @id.to_s)
    @local_tmpdir = File.basename(@remote_tmpdir)
    @package = nil
    @pid = nil
  end

  public
  def prepare()
    @package = create_package()
    node.push(@package, @id.to_s)
  end

  def spawn()
    wd = @remote_tmpdir
    sshcmd = "ssh #{@node.host} 'cd #{wd}; sh runner.sh > stdout.log 2> stderr.log'"
    puts(sshcmd)
    @pid = Process.spawn(sshcmd, :out => STDOUT, :err => STDERR)
  end

  def finalize()
    Process.waitpid(@pid) if @pid
    delete_package(@package)
  end

  def to_s()
    "#{@id}: host = #{@node.host}, params = #{@params}"
  end

  private
  def runner()
    [
      '#!/bin/sh',
      @params.map{|param| "sh command.sh #{param}"}.join("\n")
    ].join("\n")
  end

  def create_package()
    DenchPackage.create(@script_path, runner())
  end

  def delete_package(package)
    package.destroy() if package
  end
end

class Dench
  def initialize(name, yaml)
    config_hash = YAML.load(yaml)
    @yaml = yaml
    @config = DenchConfig.parse(name, config_hash)
  end

  public
  def run(script_path, parameters, outdir)
    Dir.mkdir(outdir)
    File.write(File.join(outdir, 'config.yml'), @yaml)
    nodes = @config.nodes
    processes = gen_processes(nodes, script_path, parameters)

    if @config.preprocess.dench
      @config.preprocess.dench.each do |p|
        cmd = "cd #{outdir}; #{p}"
        puts(cmd)
        system(cmd)
      end
    end
    begin
      nodes.each{|node| node.prepare()}
      (@config.preprocess.node || []).each{|p| nodes.each{|node| node.exec(p)}}
      processes.each{|process| process.prepare()}
      processes.each{|process| process.spawn()}
    ensure
      # TODO handle error
      (@config.postprocess.node || []).each{|p| nodes.each{|node| node.exec(p)}}
      nodes.each{|node| node.pullall(outdir)}
      processes.each{|process| process.finalize()}
      nodes.each{|node| node.finalize()}
    end
    if @config.postprocess.dench
      @config.postprocess.dench.each do |p|
        cmd = "cd #{outdir}; #{p}"
        puts(cmd)
        system(cmd)
      end
    end
  end

  private
  def gen_processes(nodes, script_path, parameters)
    numprocs = nodes.inject(0){|i, s| i + s.process}
    process_params = Array.new(numprocs).map{[]}
    parameters.each_with_index{|param, idx|
      process_params[idx % process_params.size].push(param)
    }
    processes = []
    nodes.map{|s| Array.new(s.process).map{s}}.flatten.each_with_index{|node, i|
      processes.push(DenchProcess.new(i, node, script_path, process_params[i]))
    }
    processes
  end
end

dench = Dench.new(name, File.read(config_path))
dench.run(script_path, parameters, output)
